"""add_favorites_indexes_and_unique_constraint

Revision ID: 105ca2a66aa4
Revises: 89151db83148
Create Date: 2026-07-24 05:45:06.939998
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '105ca2a66aa4'
down_revision: Union[str, None] = '89151db83148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_favorites_organization_id'), 'favorites', ['organization_id'], unique=False)
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_unique_constraint('uq_favorites_user_org', 'favorites', ['user_id', 'organization_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_favorites_user_org', 'favorites', type_='unique')
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_organization_id'), table_name='favorites')
    # ### end Alembic commands ###
