"""add_bio_cover_photo_city_country_to_users

Revision ID: 5fc6ffa5c623
Revises: 105ca2a66aa4
Create Date: 2026-07-24 08:29:32.154255
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '5fc6ffa5c623'
down_revision: Union[str, None] = '105ca2a66aa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cover_photo_url', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'country')
    op.drop_column('users', 'city')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'cover_photo_url')
    # ### end Alembic commands ###
