"""Add ad_campaigns and ad_analytics tables

Revision ID: 89151db83148
Revises: d712d93515f3
Create Date: 2026-07-23 23:41:53.957517
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '89151db83148'
down_revision: Union[str, None] = 'd712d93515f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_campaigns',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('campaign_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('advertiser_id', sa.UUID(), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cta_type', sa.String(length=30), nullable=True),
    sa.Column('media_url', sa.String(length=512), nullable=True),
    sa.Column('media_type', sa.String(length=10), nullable=True),
    sa.Column('destination_url', sa.String(length=512), nullable=True),
    sa.Column('placement_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('budget_type', sa.String(length=10), nullable=False),
    sa.Column('budget_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('spent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_country', sa.String(length=100), nullable=True),
    sa.Column('target_city', sa.String(length=100), nullable=True),
    sa.Column('target_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_radius_km', sa.Float(), nullable=True),
    sa.Column('target_latitude', sa.Float(), nullable=True),
    sa.Column('target_longitude', sa.Float(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('legacy_ad_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['advertiser_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['legacy_ad_id'], ['advertisements.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'campaign_type', name='uq_org_active_featured')
    )
    op.create_index(op.f('ix_ad_campaigns_campaign_type'), 'ad_campaigns', ['campaign_type'], unique=False)
    op.create_index('ix_ad_campaigns_dates', 'ad_campaigns', ['start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_ad_campaigns_organization_id'), 'ad_campaigns', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ad_campaigns_status'), 'ad_campaigns', ['status'], unique=False)
    op.create_table('ad_analytics',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=False),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.Column('whatsapp_clicks', sa.Integer(), nullable=False),
    sa.Column('website_clicks', sa.Integer(), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('spend', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['ad_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'date', name='uq_campaign_date')
    )
    op.create_index(op.f('ix_ad_analytics_campaign_id'), 'ad_analytics', ['campaign_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ad_analytics_campaign_id'), table_name='ad_analytics')
    op.drop_table('ad_analytics')
    op.drop_index(op.f('ix_ad_campaigns_status'), table_name='ad_campaigns')
    op.drop_index(op.f('ix_ad_campaigns_organization_id'), table_name='ad_campaigns')
    op.drop_index('ix_ad_campaigns_dates', table_name='ad_campaigns')
    op.drop_index(op.f('ix_ad_campaigns_campaign_type'), table_name='ad_campaigns')
    op.drop_table('ad_campaigns')
    # ### end Alembic commands ###
