"""Add is_phone_verified

Revision ID: 904fe45d89e9
Revises: c04d5e6f7081
Create Date: 2024-03-24 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '904fe45d89e9'
down_revision: Union[str, None] = 'c04d5e6f7081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_collections',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_collection_name')
    )
    op.create_index(op.f('ix_favorite_collections_user_id'), 'favorite_collections', ['user_id'], unique=False)
    op.create_table('saved_payment_methods',
    sa.Column('gateway', sa.String(length=20), nullable=False),
    sa.Column('gateway_payment_method_id', sa.String(length=255), nullable=False),
    sa.Column('last_four', sa.String(length=4), nullable=True),
    sa.Column('card_brand', sa.String(length=20), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.String(length=7), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_payment_methods_user_id'), 'saved_payment_methods', ['user_id'], unique=False)
    op.add_column('favorites', sa.Column('collection_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_favorites_collection_id'), 'favorites', ['collection_id'], unique=False)
    op.create_foreign_key('favorites_collection_id_fkey', 'favorites', 'favorite_collections', ['collection_id'], ['id'], ondelete='SET NULL')
    
    # Ownership Claims
    op.add_column('ownership_claims', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.add_column('ownership_claims', sa.Column('organization_type', sa.String(length=50), nullable=True))
    op.drop_constraint('ownership_claims_business_id_fkey', 'ownership_claims', type_='foreignkey')
    op.create_foreign_key('ownership_claims_organization_id_fkey', 'ownership_claims', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_column('ownership_claims', 'business_id')

    # Users
    op.add_column('users', sa.Column('is_phone_verified', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET is_phone_verified = FALSE")
    op.alter_column('users', 'is_phone_verified', nullable=False)

    # Organization Managers
    op.drop_constraint('uq_organization_single_manager', 'organization_managers', type_='unique')
    op.create_unique_constraint('uq_organization_user_manager', 'organization_managers', ['organization_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_organization_user_manager', 'organization_managers', type_='unique')
    op.create_unique_constraint('uq_organization_single_manager', 'organization_managers', ['organization_id'])
    
    op.drop_column('users', 'is_phone_verified')

    op.add_column('ownership_claims', sa.Column('business_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint('ownership_claims_organization_id_fkey', 'ownership_claims', type_='foreignkey')
    op.create_foreign_key('ownership_claims_business_id_fkey', 'ownership_claims', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.drop_column('ownership_claims', 'organization_type')
    op.drop_column('ownership_claims', 'organization_id')

    op.drop_constraint('favorites_collection_id_fkey', 'favorites', type_='foreignkey')
    op.drop_index(op.f('ix_favorites_collection_id'), table_name='favorites')
    op.drop_column('favorites', 'collection_id')
    op.drop_index(op.f('ix_saved_payment_methods_user_id'), table_name='saved_payment_methods')
    op.drop_table('saved_payment_methods')
    op.drop_index(op.f('ix_favorite_collections_user_id'), table_name='favorite_collections')
    op.drop_table('favorite_collections')
    # ### end Alembic commands ###
