"""Add organization_posts and post_likes tables

Revision ID: d712d93515f3
Revises: 11d7365e3d62
Create Date: 2026-07-23 21:58:11.719027
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd712d93515f3'
down_revision: Union[str, None] = '11d7365e3d62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_providers',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('organization_posts',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_likes',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['organization_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('uq_organization_manager'), 'organization_managers', type_='unique')
    op.create_unique_constraint('uq_organization_single_manager', 'organization_managers', ['organization_id'])
    op.drop_column('organization_managers', 'permissions')
    op.add_column('payments', sa.Column('reference_type', sa.String(length=50), nullable=True))
    op.add_column('payments', sa.Column('reference_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_payments_reference_id'), 'payments', ['reference_id'], unique=False)
    op.create_index(op.f('ix_payments_reference_type'), 'payments', ['reference_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_reference_type'), table_name='payments')
    op.drop_index(op.f('ix_payments_reference_id'), table_name='payments')
    op.drop_column('payments', 'reference_id')
    op.drop_column('payments', 'reference_type')
    op.add_column('organization_managers', sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint('uq_organization_single_manager', 'organization_managers', type_='unique')
    op.create_unique_constraint(op.f('uq_organization_manager'), 'organization_managers', ['organization_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.drop_table('post_likes')
    op.drop_table('organization_posts')
    op.drop_table('payment_providers')
    # ### end Alembic commands ###
