"""add_image_urls_to_reviews

Revision ID: dbd69730a19d
Revises: 5fc6ffa5c623
Create Date: 2026-07-24 08:40:23.618980
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'dbd69730a19d'
down_revision: Union[str, None] = '5fc6ffa5c623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'image_urls')
    # ### end Alembic commands ###
