import uuid

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.core.database import get_db
from app.core.dependencies import get_current_user, require_email_verified, require_permission
from app.models.charity import Charity, CharityCampaign
from app.models.donation import Donation
from app.models.organization import Organization
from app.models.payment import Payment
from app.models.user import User
from app.payments import get_gateway
from app.schemas.common import PaginatedResponse
from app.schemas.donation import DonationInitiate
from app.services.audit_service import log_action
from app.services.email_service import render_email_template, send_email
from app.services.notification_service import create_notification

router = APIRouter()


def _generate_pdf_receipt(donation, charity_name: str, campaign_title: str | None) -> bytes:
    from fpdf import FPDF
    from datetime import datetime
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 15, "Umma Directory", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Donation Receipt", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, f"Receipt Number: {donation.receipt_number or 'N/A'}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, f"Date: {donation.created_at.strftime('%Y-%m-%d %H:%M') if donation.created_at else 'N/A'}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, f"Amount: {donation.amount} {donation.currency}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, f"Charity: {charity_name}", new_x="LMARGIN", new_y="NEXT")
    if campaign_title:
        pdf.cell(0, 8, f"Campaign: {campaign_title}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, f"Status: {donation.status}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, f"Anonymous: {'Yes' if donation.is_anonymous else 'No'}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 9)
    pdf.cell(0, 5, "Thank you for your donation.", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, "This receipt is auto-generated by Umma Directory.", align="C", new_x="LMARGIN", new_y="NEXT")
    return bytes(pdf.output())


@router.post("/initiate")
async def initiate_donation(
    req: DonationInitiate,
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
    _: User = Depends(require_email_verified()),
    __: User = Depends(require_permission("donation.create")),
):

    if req.amount < settings.min_donation_amount:
        raise HTTPException(
            status_code=400,
            detail=f"Minimum donation amount is {settings.min_donation_amount} {req.currency}",
        )

    organization_id = None
    campaign = None
    org_name = ""

    # Path 1: Donation via a campaign
    if req.campaign_id:
        campaign_result = await db.execute(
            select(CharityCampaign).where(CharityCampaign.id == req.campaign_id)
        )
        campaign = campaign_result.scalar_one_or_none()
        if not campaign:
            raise HTTPException(status_code=404, detail="Campaign not found")
        if campaign.status != "active":
            raise HTTPException(status_code=400, detail="Campaign is not active")

        charity_result = await db.execute(
            select(Charity).where(Charity.id == campaign.charity_id, Charity.is_verified)
        )
        charity = charity_result.scalar_one_or_none()
        if not charity:
            raise HTTPException(status_code=400, detail="Charity is not verified")

        organization_id = campaign.charity_id
        org_name = charity.name

    # Path 2: Direct donation to a verified organization
    elif req.organization_id:
        org_uuid = uuid.UUID(req.organization_id) if isinstance(req.organization_id, str) else req.organization_id
        org = await db.get(Organization, org_uuid)
        if not org:
            raise HTTPException(status_code=404, detail="Organization not found")
        if org.status != "approved":
            raise HTTPException(status_code=400, detail="Organization is not approved for donations")
        organization_id = org.id
        org_name = org.name
    else:
        raise HTTPException(status_code=400, detail="Either campaign_id or organization_id is required")

    if req.idempotency_key:
        existing = await db.execute(
            select(Donation).where(Donation.idempotency_key == req.idempotency_key)
        )
        existing_donation = existing.scalar_one_or_none()
        if existing_donation:
            return {
                "donation_id": str(existing_donation.id),
                "receipt_number": existing_donation.receipt_number,
                "message": "Donation already initiated",
                "status": existing_donation.status,
            }

    receipt = f"DON-{uuid.uuid4().hex[:12].upper()}"
    donation = Donation(
        amount=req.amount,
        currency=req.currency,
        is_anonymous=req.is_anonymous,
        receipt_number=receipt,
        idempotency_key=req.idempotency_key,
        donor_id=user.id,
        organization_id=organization_id,
        campaign_id=campaign.id if campaign else None,
        status="pending",
    )
    db.add(donation)
    await db.flush()

    try:
        gw = get_gateway(req.payment_gateway)
        intent = await gw.create_payment(
            req.amount, req.currency,
            {"donation_id": str(donation.id), "organization": org_name},
        )

        payment = Payment(
            amount=req.amount,
            currency=req.currency,
            gateway=req.payment_gateway,
            gateway_payment_id=intent.gateway_payment_id,
            status="pending",
            user_id=user.id,
        )
        db.add(payment)

        donation.payment_id = payment.id
        await db.flush()

        await log_action(db, user.id, "donation.initiate", "donation", str(donation.id))

        return {
            "donation_id": str(donation.id),
            "payment_id": str(payment.id),
            "receipt_number": receipt,
            "gateway_payment_id": intent.gateway_payment_id,
            "client_secret": intent.client_secret,
            "approval_url": intent.approval_url,
            "status": "pending",
        }
    except Exception as e:
        donation.status = "failed"
        raise HTTPException(status_code=400, detail="Payment processing failed. Please try again.")


@router.post("/{id}/confirm")
async def confirm_donation(
    id: str,
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(select(Donation).where(Donation.id == id))
    donation = result.scalar_one_or_none()
    if not donation:
        raise HTTPException(status_code=404, detail="Donation not found")

    if str(donation.donor_id) != str(user.id):
        raise HTTPException(status_code=403, detail="Not your donation")

    if donation.status != "pending":
        raise HTTPException(status_code=400, detail="Donation already processed")

    payment_result = await db.execute(select(Payment).where(Payment.id == donation.payment_id))
    payment = payment_result.scalar_one_or_none()

    if payment and payment.status == "succeeded":
        donation.status = "completed"

        # Update campaign raised amount if applicable
        campaign = None
        if donation.campaign_id:
            campaign_res = await db.execute(
                select(CharityCampaign).where(CharityCampaign.id == donation.campaign_id)
            )
            campaign = campaign_res.scalar_one_or_none()
            if campaign:
                campaign.amount_raised = (campaign.amount_raised or 0) + donation.amount

        # Get organization name for notifications
        org_name = ""
        if donation.organization_id:
            org_result = await db.execute(select(Organization).where(Organization.id == donation.organization_id))
            org_obj = org_result.scalar_one_or_none()
            if org_obj:
                org_name = org_obj.name

        await create_notification(
            db, str(donation.donor_id), "donation.confirmed",
            "Donation confirmed",
            f"Your donation of {donation.amount} {donation.currency} to {campaign.title if campaign else org_name} was successful.",
        )

        email_html = render_email_template(
            "donation_receipt",
            amount=f"{donation.amount} {donation.currency}",
            charity=org_name,
            receipt=donation.receipt_number,
        )
        await send_email(user.email, "Donation Confirmed", email_html)

        await log_action(db, user.id, "donation.confirm", "donation", id)
        return {"message": "Donation confirmed", "status": "completed"}

    return {"message": "Payment not yet confirmed", "status": donation.status}


@router.get("/history", response_model=PaginatedResponse)
async def donation_history(
    page: int = Query(1, ge=1),
    size: int = Query(20, ge=1, le=100),
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    query = select(Donation).where(Donation.donor_id == user.id).order_by(Donation.created_at.desc())
    total = (await db.execute(select(func.count()).select_from(query.subquery()))).scalar() or 0
    query = query.offset((page - 1) * size).limit(size)
    result = await db.execute(query)

    return PaginatedResponse(
        items=[{
            "id": str(d.id), "amount": str(d.amount),
            "currency": d.currency, "status": d.status,
            "receipt_number": d.receipt_number,
            "is_anonymous": d.is_anonymous,
            "organization_id": str(d.organization_id),
            "campaign_id": str(d.campaign_id) if d.campaign_id else None,
            "created_at": d.created_at,
        } for d in result.scalars().all()],
        total=total, page=page, size=size, pages=(total + size - 1) // size,
    )


@router.get("/{id}/receipt/pdf")
async def download_receipt_pdf(
    id: str,
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    from fastapi.responses import Response
    result = await db.execute(select(Donation).where(Donation.id == id))
    donation = result.scalar_one_or_none()
    if not donation:
        raise HTTPException(status_code=404, detail="Donation not found")
    if str(donation.donor_id) != str(user.id):
        raise HTTPException(status_code=403, detail="Not your donation")

    campaign = None
    org_name = ""
    if donation.campaign_id:
        c_result = await db.execute(
            select(CharityCampaign).where(CharityCampaign.id == donation.campaign_id)
        )
        campaign = c_result.scalar_one_or_none()
    if donation.organization_id:
        org_result = await db.execute(select(Organization).where(Organization.id == donation.organization_id))
        org_obj = org_result.scalar_one_or_none()
        if org_obj:
            org_name = org_obj.name

    pdf_bytes = _generate_pdf_receipt(donation, org_name, campaign.title if campaign else None)
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="receipt-{donation.receipt_number or donation.id}.pdf"'},
    )


@router.get("/{id}/receipt")
async def get_receipt(
    id: str,
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(select(Donation).where(Donation.id == id))
    donation = result.scalar_one_or_none()
    if not donation:
        raise HTTPException(status_code=404, detail="Donation not found")
    if str(donation.donor_id) != str(user.id):
        raise HTTPException(status_code=403, detail="Not your donation")

    campaign = None
    org_name = ""
    if donation.campaign_id:
        c_result = await db.execute(
            select(CharityCampaign).where(CharityCampaign.id == donation.campaign_id)
        )
        campaign = c_result.scalar_one_or_none()
    if donation.organization_id:
        org_result = await db.execute(select(Organization).where(Organization.id == donation.organization_id))
        org_obj = org_result.scalar_one_or_none()
        if org_obj:
            org_name = org_obj.name

    return {
        "receipt_number": donation.receipt_number,
        "donation_date": donation.created_at,
        "amount": str(donation.amount),
        "currency": donation.currency,
        "organization_name": org_name,
        "campaign_name": campaign.title if campaign else None,
        "status": donation.status,
        "is_anonymous": donation.is_anonymous,
    }


@router.get("/campaign/{campaign_id}")
async def campaign_donations(
    campaign_id: str,
    page: int = Query(1, ge=1),
    size: int = Query(20, ge=1, le=100),
    db: AsyncSession = Depends(get_db),
):
    query = select(Donation).where(
        Donation.campaign_id == campaign_id,
        Donation.status == "completed",
    ).order_by(Donation.created_at.desc())
    total = (await db.execute(select(func.count()).select_from(query.subquery()))).scalar() or 0
    query = query.offset((page - 1) * size).limit(size)
    result = await db.execute(query)
    return PaginatedResponse(
        items=[{
            "id": str(d.id), "amount": str(d.amount),
            "currency": d.currency, "receipt_number": d.receipt_number,
            "is_anonymous": d.is_anonymous,
            "created_at": d.created_at,
        } for d in result.scalars().all()],
        total=total, page=page, size=size, pages=(total + size - 1) // size,
    )


@router.get("/stats")
async def donation_stats(
    db: AsyncSession = Depends(get_db),
    user: User = Depends(get_current_user),
):
    total_q = await db.execute(
        select(func.count(), func.sum(Donation.amount))
        .where(Donation.status == "completed")
    )
    row = total_q.one()
    return {
        "total_donations": row[0] or 0,
        "total_amount": str(row[1] or 0),
    }
